### ISSUE TITLE
Group metrics not available

### ISSUE THREAD

**Issue by andrepnh** [rbraeunlich/gatling-jdbc#2]
I have a simulation that does something similar to:

```scala
scenario("A scenario")
  .group("SQL group") {
    exec().asLongAs(someCondition) {
      exec(jdbc("Some SQL")
        .select("*")
        .from("Table"))
    }
  }.inject(atOnceUsers(1))
```
And I'm trying to assert the response time for the entire group using `details("SQL group").responseTime.max.lt(1000)`. But the assertion never fails because the group response time is always reported as 0 in the highcharts reports. When I checked the simulation log I could see the same situation:

```
GROUP	1	Request group	1554911858984	1554912040665	0	OK
```

But for groups using http calls I can see the response time in the logs:

```
GROUP	144	Http Group	1554911873092	1554911876653	3561	OK
```

I'm using version 2.2.0, gatling 3.0.3. Please let me know if more details are needed and thanks for creating the library, it's really helpful for the use case I have 👍

**Comment by rbraeunlich** [comment]
Hi @andrepnh 
first of all sorry for the late reply and thank you for the praise.
If you execute the select without using the group wrapper, does it report the times correctly?
Cheers,
Ronny

**Comment by andrepnh** [comment]
@rbraeunlich times for individual requests are reported correctly, but for the actual simulation I use the group has multiple `exec` calls. Those calls all serve the same bigger purpose, so grouping the metrics help me analyze performance at a higher level.

**Comment by rbraeunlich** [comment]
Hey @andrepnh 
I finally found the time to fix the bug. I'll try to release a bugfix version latest on Sunday.
Cheers,
Ronny
