### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/collection/compat/Factory$

### ISSUE THREAD

**Issue by kunalbuddy** [rbraeunlich/gatling-jdbc#3]
Hi all,
i was running the gatling from intellij idea.please find the files used attached. Engine is the main scala class and test is running the test cases.

 

[Archive.zip](https://github.com/rbraeunlich/gatling-jdbc/files/3115284/Archive.zip)

**Comment by rbraeunlich** [comment]
Hey @kunalbuddy,
could you maybe add your build.sbt?
Cheers,
Ronny

**Comment by aklexel** [comment]
I have the same error with Gatling version 3.1.0 and higher. Everything works fine only with Gatling version 3.0.3.

To reproduce the issue just run the tests of the jdbc-gatling project.

**Comment by aklexel** [comment]
As workaround for Gatling 3.1.2 you can add 

libraryDependencies += "org.scalikejdbc" %% "scalikejdbc" % "3.4.0-RC1"

in your build.sbt. But in Gatling version 3.1.3 and higher you will get another error (

**Comment by rbraeunlich** [comment]
Hi @aklexel 
sorry for the late reply. How do you start the simulation? Using Gatling standalone or via a plugin?

**Comment by aklexel** [comment]
Hi @rbraeunlich 
I use the gatling-sbt plugin to launch Gatling simulations.

**Comment by rbraeunlich** [comment]
Hi @aklexel 
habe you tried running your simulations with the new version?
