### ISSUE TITLE
Repository link

### ISSUE THREAD

**Issue by demwis** [rbraeunlich/gatling-jdbc#4]
Hi, Ronny.

Could you please advise, which repository I can use to download dependency on the library using Gradle? Seems, the standard maven repository doesn't contain the latest artifacts.

Best regards,
Dmitriy

**Comment by rbraeunlich** [comment]
Hey @demwis 
sorry for the late reply. Which artifact are you missing?
The latest 2.2.1 release is on Maven central https://search.maven.org/artifact/dev.code-n-roll.gatling/jdbc-gatling_2.12/2.2.1/jar
